// -----------------------------------------------------------------------------
// MARK: Data
// -----------------------------------------------------------------------------

const CLASS_NAME = {
    void_warden: "Guardienne du Néant",
    red_guard: "Guarde Rouge",
};

const MAX_HP_MAP = {
    void_warden: [6, 7, 8, 9, 10, 11, 12, 13, 14],
    red_guard: [10, 12, 14, 16, 18, 20, 22, 24, 26],
};

const MAX_CARD_MAP = {
    void_warden: 11,
    red_guard: 10,
};

const BOSS_ACTIONS = [
    {
        id: 1,
        name: "Puissance Accélérée",
        initiative: 11,
        recycled: false,
        effects: ["Spécial 2"],
    },
    {
        id: 2,
        name: "Puissance Accélérée",
        initiative: 14,
        recycled: false,
        effects: ["Spécial 2"],
    },
    {
        id: 3,
        name: "Puissance Accélérée",
        initiative: 17,
        recycled: true,
        effects: ["Spécial 2"],
    },
    {
        id: 4,
        name: "Force Durable",
        initiative: 85,
        recycled: true,
        effects: ["Spécial 1"],
    },
    {
        id: 5,
        name: "Force Durable",
        initiative: 79,
        recycled: false,
        effects: ["Spécial 1"],
    },
    {
        id: 6,
        name: "Force Durable",
        initiative: 73,
        recycled: false,
        effects: ["Spécial 1"],
    },
    {
        id: 7,
        name: "Rien de particulier",
        initiative: 36,
        recycled: false,
        effects: ["Déplacement +0", "Attaque +0"],
    },
    {
        id: 8,
        name: "Projectiles Jumeaux",
        initiative: 54,
        recycled: false,
        effects: ["Déplacement -1", "Attaque -1, portée 3, cible 2"],
    },
];

const ENEMIES = [
    {
        id: "reanimated_corpse",
        name: "Cadavre Réanimé",
        normalHp: [5, 7, 9, 10, 11, 13, 14, 16],
        eliteHp: [10, 11, 14, 14, 16, 18, 23, 29],
        normalMove: [1, 1, 1, 1, 2, 2, 2, 2],
        eliteMove: [1, 1, 1, 2, 2, 2, 2, 2],
        normalAttack: [3, 3, 3, 4, 4, 4, 4, 5],
        eliteAttack: [3, 4, 4, 5, 5, 6, 6, 6],
        normalModifiers: [
            "",
            "",
            "",
            "",
            "",
            "",
            "empoisonnement",
            "empoisonnement",
        ],
        eliteModifiers: [
            "",
            "",
            "",
            "",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "Empoisonnement",
        ],
        actions: [
            {
                id: 1,
                name: "Étreinte putride",
                initiative: 21,
                recycled: false,
                effects: [
                    "Déplacement +1",
                    "Confusion, immobilisation (cible un adversaire adjacents)",
                    "consume terre: cible subit aussi 2 dégats",
                ],
            },
            {
                id: 2,
                name: "Claque violente",
                initiative: 32,
                recycled: false,
                effects: [
                    "Attaque +2, poussée 1",
                    "Si attaque est effectuée, le cadavre réanimé subit 1 dégat",
                ],
            },
            {
                id: 3,
                name: "Assaut précipité",
                initiative: 47,
                recycled: false,
                effects: ["Déplacement +1", "Attaque -1"],
            },
            {
                id: 4,
                name: "Rien de particulier",
                initiative: 68,
                recycled: true,
                effects: ["Déplacement +0", "Attaque +0"],
            },
            {
                id: 5,
                name: "Rien de particulier",
                initiative: 68,
                recycled: true,
                effects: ["Déplacement +0", "Attaque +0"],
            },
            {
                id: 6,
                name: "Émission de gaz",
                initiative: 71,
                recycled: false,
                effects: [
                    "Déplacement +0",
                    "Attaque +1",
                    "Empoisonnement (cible tous adversaires adjacents)",
                    "Infuse terre",
                ],
            },
            {
                id: 7,
                name: "Coup calculé",
                initiative: 81,
                recycled: false,
                effects: ["Déplacement -1", "Attaque +1"],
            },
            {
                id: 8,
                name: "Charge téméraire",
                initiative: 91,
                recycled: false,
                effects: [
                    "Déplacement -2",
                    "Si ce déplacement est effectué, cadavre subit 1 dégat",
                ],
            },
        ],
    },
    {
        id: "chaos_demon",
        name: "Démon du Chaos",
        normalHp: [7, 8, 11, 12, 15, 16, 20, 22],
        eliteHp: [10, 12, 14, 18, 21, 26, 30, 35],
        normalMove: [3, 3, 3, 3, 4, 4, 4, 4],
        eliteMove: [4, 4, 4, 5, 5, 5, 5, 5],
        normalAttack: [2, 3, 3, 4, 4, 5, 5, 6],
        eliteAttack: [3, 4, 5, 5, 6, 6, 7, 8],
        normalModifiers: [
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
        ],
        eliteModifiers: [
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
        ],
        actions: [
            {
                id: 1,
                name: "Souffle Glacial",
                initiative: 13,
                recycled: false,
                effects: [
                    "Déplacement -1",
                    "Attaque +0, cible 2 hex voisins adjacents",
                    "Infuse glace: chaque fois qu'un héro attaque le démon, le héro subit 2 dégats",
                ],
            },
            {
                id: 2,
                name: "Déflagration de Chaleur",
                initiative: 1,
                recycled: false,
                effects: [
                    "Déplacement -1",
                    "Attaque -1, portée 3",
                    "Consume feu: blessure",
                ],
            },
            {
                id: 3,
                name: "Coup sismique",
                initiative: 67,
                recycled: false,
                effects: [
                    "Déplacement -2",
                    "Attaque +1, poussée 2",
                    "Consume terre: cible 2 hex adjacents voisins",
                ],
            },
            {
                id: 4,
                name: "Tourbillon",
                initiative: 20,
                recycled: false,
                effects: [
                    "Déplacement +0",
                    "Attaque -1, portée 2, cible 3 hex adjacents voisins",
                    "Consume air: bouclier 2",
                ],
            },
            {
                id: 5,
                name: "Griffes Soudaines",
                initiative: 41,
                recycled: false,
                effects: [
                    "Déplacement +0",
                    "Attaque +0, avantage",
                    "Consume lumière: soin 4 sur lui-même",
                ],
            },
            {
                id: 6,
                name: "Vrilles Noires",
                initiative: 52,
                recycled: false,
                effects: [
                    "Déplacement -1",
                    "Attaque +1",
                    "Consume obscurité: tous les adversaires adjacents à cible subissent 1 dégat",
                ],
            },
            {
                id: 7,
                name: "Explosion de Mana",
                initiative: 76,
                recycled: true,
                effects: [
                    "Déplacement +0",
                    "Attaque +0",
                    "Infuse feu, glace, air, terre, lumière, obscurité",
                ],
            },
            {
                id: 8,
                name: "Gueule Affamée",
                initiative: 98,
                recycled: true,
                effects: [
                    "Attaque -1",
                    "Consume n'importe quel élément: désarmement",
                ],
            },
        ],
    },
    {
        id: "blood_demon",
        name: "Diablotin de Sang",
        normalHp: [3, 4, 5, 5, 7, 8, 9, 12],
        eliteHp: [4, 6, 7, 10, 11, 13, 17, 21],
        normalMove: [2, 2, 3, 3, 3, 4, 4, 4],
        eliteMove: [2, 2, 3, 3, 3, 4, 4, 4],
        normalAttack: [1, 1, 1, 2, 2, 2, 3, 3],
        eliteAttack: [2, 2, 2, 2, 3, 3, 4, 4],
        normalModifiers: [
            "",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
        ],
        eliteModifiers: [
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
            "confusion",
        ],
        actions: [
            {
                id: 1,
                name: "Hors phase",
                initiative: 5,
                recycled: false,
                effects: [
                    "Bouclier 5",
                    "Soin 1 sur lui même",
                    "Infuse 1 élément",
                ],
            },
            {
                id: 2,
                name: "Faire pencher la balance",
                initiative: 24,
                recycled: false,
                effects: [
                    "Renforcement, cible tous aliés portée 2 et lui-même",
                    "Confusion, cible tous adversaires à portée 2",
                ],
            },
            {
                id: 3,
                name: "Rien de particulier",
                initiative: 37,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0, portée 3"],
            },
            {
                id: 4,
                name: "Rien de particulier",
                initiative: 37,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0, portée 3"],
            },
            {
                id: 5,
                name: "Récupération",
                initiative: 42,
                recycled: true,
                effects: ["Déplacement +1", "Soin 2, portée 3"],
            },
            {
                id: 6,
                name: "Estropier",
                initiative: 42,
                recycled: true,
                effects: [
                    "Déplacement +0",
                    "Attaque -1, portée 2, cible 2, empoisonnement",
                ],
            },
            {
                id: 7,
                name: "Sombre charme",
                initiative: 42,
                recycled: false,
                effects: [
                    "Déplacement +0",
                    "Attaque -1, portée 3, cible 2, malédiction",
                ],
            },
            {
                id: 8,
                name: "Coup calculé",
                initiative: 76,
                recycled: false,
                effects: ["Déplacement -1", "Attaque +1, portée 3"],
            },
        ],
    },
    {
        id: "black_imp",
        name: "Diablotin Noir",
        normalHp: [3, 4, 5, 5, 7, 9, 10, 13],
        eliteHp: [4, 6, 8, 8, 11, 14, 15, 19],
        normalMove: [1, 1, 1, 1, 1, 1, 1, 1],
        eliteMove: [1, 1, 1, 1, 1, 1, 1, 1],
        normalAttack: [1, 1, 1, 2, 2, 2, 3, 3],
        eliteAttack: [2, 2, 2, 3, 3, 3, 4, 4],
        normalModifiers: [
            "",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
        ],
        eliteModifiers: [
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement, attaquants gagnent désavantage",
            "empoisonnement, attaquants gagnent désavantage",
            "empoisonnement, attaquants gagnent désavantage",
            "empoisonnement, attaquants gagnent désavantage",
            "empoisonnement, attaquants gagnent désavantage",
        ],
        actions: [
            {
                id: 1,
                name: "Hors phase",
                initiative: 5,
                recycled: false,
                effects: [
                    "Bouclier 5",
                    "Soin 1 sur lui même",
                    "Infuse 1 élément",
                ],
            },
            {
                id: 2,
                name: "Faire pencher la balance",
                initiative: 24,
                recycled: false,
                effects: [
                    "Renforcement, cible tous aliés portée 2 et lui-même",
                    "Confusion, cible tous adversaires à portée 2",
                ],
            },
            {
                id: 3,
                name: "Rien de particulier",
                initiative: 37,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0, portée 3"],
            },
            {
                id: 4,
                name: "Rien de particulier",
                initiative: 37,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0, portée 3"],
            },
            {
                id: 5,
                name: "Récupération",
                initiative: 42,
                recycled: true,
                effects: ["Déplacement +1", "Soin 2, portée 3"],
            },
            {
                id: 6,
                name: "Estropier",
                initiative: 42,
                recycled: true,
                effects: [
                    "Déplacement +0",
                    "Attaque -1, portée 2, cible 2, empoisonnement",
                ],
            },
            {
                id: 7,
                name: "Sombre charme",
                initiative: 42,
                recycled: false,
                effects: [
                    "Déplacement +0",
                    "Attaque -1, portée 3, cible 2, malédiction",
                ],
            },
            {
                id: 8,
                name: "Coup calculé",
                initiative: 76,
                recycled: false,
                effects: ["Déplacement -1", "Attaque +1, portée 3"],
            },
        ],
    },
    {
        id: "vermling_scout",
        name: "Éclaireur Vermling",
        normalHp: [2, 3, 3, 5, 6, 8, 10, 13],
        eliteHp: [4, 5, 5, 7, 8, 11, 13, 17],
        normalMove: [3, 3, 3, 3, 3, 3, 4, 4],
        eliteMove: [3, 3, 4, 4, 4, 4, 5, 5],
        normalAttack: [1, 1, 2, 2, 3, 3, 3, 3],
        eliteAttack: [2, 2, 3, 3, 4, 4, 4, 4],
        normalModifiers: ["", "", "", "", "", "", "", ""],
        eliteModifiers: ["", "", "", "", "", "", "", ""],
        actions: [
            {
                id: 1,
                name: "Arc court",
                initiative: 29,
                recycled: false,
                effects: ["Déplacement -1", "Attaque -1, portée 3"],
            },
            {
                id: 2,
                name: "Assaut précipité",
                initiative: 40,
                recycled: false,
                effects: ["Déplacement +1", "Attaque -1"],
            },
            {
                id: 3,
                name: "Rien de particulier",
                initiative: 53,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0"],
            },
            {
                id: 4,
                name: "Flèche rance",
                initiative: 53,
                recycled: false,
                effects: [
                    "Déplacement -2",
                    "Attaque +0, portée 3, empoisonnement",
                ],
            },
            {
                id: 5,
                name: "Coup calculé",
                initiative: 69,
                recycled: false,
                effects: ["Déplacement -1", "Attaque +1"],
            },
            {
                id: 6,
                name: "Lame délétère",
                initiative: 92,
                recycled: true,
                effects: ["Attaque +2, empoisonnement"],
            },
            {
                id: 7,
                name: "Carreaux rapides",
                initiative: 78,
                recycled: false,
                effects: ["Attaque -1, portée 4, cible 2"],
            },
            {
                id: 8,
                name: "Avidité",
                initiative: 40,
                recycled: true,
                effects: ["Déplacement +1, saut", "Pillage 1"],
            },
        ],
    },
    {
        id: "reanimated_spirit",
        name: "Esprit Réanimé",
        normalHp: [3, 4, 5, 6, 6, 8, 9, 12],
        eliteHp: [5, 5, 7, 8, 8, 11, 13, 17],
        normalMove: [2, 2, 3, 3, 3, 3, 3, 3],
        eliteMove: [3, 3, 4, 4, 4, 4, 4, 4],
        normalAttack: [2, 2, 2, 3, 3, 3, 4, 4],
        eliteAttack: [3, 3, 3, 4, 4, 4, 5, 5],
        normalModifiers: [
            "Bouclier 1",
            "Bouclier 1",
            "Bouclier 1",
            "Bouclier 1",
            "Bouclier 2",
            "Bouclier 2",
            "Bouclier 2",
            "Bouclier 2",
        ],
        eliteModifiers: [
            "Bouclier 1",
            "Bouclier 2",
            "Bouclier 2",
            "Bouclier 2",
            "Bouclier 3",
            "Bouclier 3",
            "Bouclier 3",
            "Bouclier 3",
        ],
        actions: [
            {
                id: 1,
                name: "Saper l'énergie",
                initiative: 22,
                recycled: true,
                effects: ["Déplacement -1", "Attaque -1, portée 4, confusion"],
            },
            {
                id: 2,
                name: "Cri retentissant",
                initiative: 33,
                recycled: true,
                effects: [
                    "Déplacement +0",
                    "Attaque -1, cible tous adversaires à portée 2",
                ],
            },
            {
                id: 3,
                name: "Rien de particulier",
                initiative: 48,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0, portée 3"],
            },
            {
                id: 4,
                name: "Rien de particulier",
                initiative: 48,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0, portée 3"],
            },
            {
                id: 5,
                name: "Chaine couplée",
                initiative: 61,
                recycled: false,
                effects: ["Attaque +0, portée 3, cible 2"],
            },
            {
                id: 6,
                name: "Aspirer la chaleur",
                initiative: 75,
                recycled: false,
                effects: [
                    "Déplacement -1",
                    "Attaque +1, portée 3",
                    "Soin 1 sur lui-même",
                    "Infuse Glace",
                ],
            },
            {
                id: 7,
                name: "Hurlement de colère",
                initiative: 55,
                recycled: false,
                effects: [
                    "Déplacement +0",
                    "Malédiction, cible tous les adversaires à portée 3",
                    "Infuse glace",
                ],
            },
            {
                id: 8,
                name: "Regard glacial",
                initiative: 67,
                recycled: false,
                effects: [
                    "Déplacement -1",
                    "Attaque +1, portée 3",
                    "Infuse glace: désarmement",
                ],
            },
        ],
    },
    {
        id: "stone_golem",
        name: "Golem de Pierre",
        normalHp: [10, 10, 11, 11, 12, 13, 16, 16],
        eliteHp: [10, 11, 13, 14, 16, 18, 20, 21],
        normalMove: [1, 1, 1, 1, 2, 2, 2, 2],
        eliteMove: [2, 2, 2, 2, 2, 3, 3, 3],
        normalAttack: [3, 3, 4, 4, 4, 5, 5, 5],
        eliteAttack: [4, 4, 5, 5, 6, 6, 7, 7],
        normalModifiers: [
            "",
            "Bouclier 1",
            "Bouclier 1",
            "Bouclier 2",
            "Bouclier 2",
            "Bouclier 2",
            "Bouclier 2",
            "Bouclier 3",
        ],
        eliteModifiers: [
            "Bouclier 1",
            "Bouclier 2",
            "Bouclier 2",
            "Bouclier 3",
            "Bouclier 3",
            "Bouclier 3",
            "Bouclier 3",
            "Bouclier 4",
        ],
        actions: [
            {
                id: 1,
                name: "Progression éprouvante",
                initiative: 28,
                recycled: false,
                effects: [
                    "Déplacement +1",
                    "Attack +1",
                    "Si la capacité de déplacement a été effectuée, le golem subit 1 dégat",
                ],
            },
            {
                id: 2,
                name: "Assaut précipité",
                initiative: 51,
                recycled: true,
                effects: ["Déplacement +1", "Attack -1"],
            },
            {
                id: 3,
                name: "Marteler le sol",
                initiative: 83,
                recycled: false,
                effects: [
                    "Déplacement +0",
                    "Attack -1 (cible tous les adversaires adjacents",
                ],
            },
            {
                id: 4,
                name: "Coup calculé",
                initiative: 90,
                recycled: true,
                effects: ["Déplacement -1", "Attack +1"],
            },
            {
                id: 5,
                name: "Réaction runique",
                initiative: 10,
                recycled: false,
                effects: [
                    "Chaque fois qu'un héro attaque le golem, le héro subit 3 dégats",
                ],
            },
            {
                id: 6,
                name: "Attraction runique",
                initiative: 28,
                recycled: false,
                effects: [
                    "Déplacement +1",
                    "Attaque -2 (portée 3), traction 2, immobilisation",
                ],
            },
            {
                id: 7,
                name: "Rien de particulier",
                initiative: 64,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0"],
            },
            {
                id: 8,
                name: "Lancer sacrificiel",
                initiative: 72,
                recycled: false,
                effects: [
                    "Attaque +1 (portée 3). Si attaque est effectuée, le golem subit 2 dégats",
                ],
            },
        ],
    },
    {
        id: "blood_monster",
        name: "Monstruosité de Sang",
        normalHp: [7, 9, 10, 12, 12, 13, 17, 20],
        eliteHp: [12, 12, 15, 18, 18, 20, 23, 23],
        normalMove: [2, 2, 2, 3, 3, 3, 3, 3],
        eliteMove: [2, 2, 2, 3, 3, 3, 3, 3],
        normalAttack: [2, 2, 3, 3, 3, 4, 4, 5],
        eliteAttack: [3, 3, 4, 4, 4, 5, 6, 6],
        normalModifiers: [
            "à sa mort, tous les personnages adjacents subissent 1 dégats",
            "à sa mort, tous les personnages adjacents subissent 2 dégats",
            "à sa mort, tous les personnages adjacents subissent 2 dégats",
            "à sa mort, tous les personnages adjacents subissent 3 dégats",
            "à sa mort, tous les personnages adjacents subissent 3 dégats, Bouclier 1",
            "à sa mort, tous les personnages adjacents subissent 3 dégats, Bouclier 1",
            "à sa mort, tous les personnages adjacents subissent 3 dégats, Bouclier 1",
            "à sa mort, tous les personnages adjacents subissent 4 dégats, Bouclier 1",
        ],
        eliteModifiers: [
            "à sa mort, tous les personnages adjacents subissent 1 dégats",
            "à sa mort, tous les personnages adjacents subissent 3 dégats, Bouclier 1",
            "à sa mort, tous les personnages adjacents subissent 3 dégats, Bouclier 1",
            "à sa mort, tous les personnages adjacents subissent 4 dégats, Bouclier 1",
            "à sa mort, tous les personnages adjacents subissent 4 dégats, Bouclier 2",
            "à sa mort, tous les personnages adjacents subissent 5 dégats, Bouclier 2",
            "à sa mort, tous les personnages adjacents subissent 5 dégats, Bouclier 2",
            "à sa mort, tous les personnages adjacents subissent 5 dégats, Bouclier 3",
        ],
        actions: [
            {
                id: 1,
                name: "Bulles explosives",
                initiative: 9,
                recycled: true,
                effects: [
                    "Déplacement +1",
                    "Chaque fois qu'un héro attaque la monstruosité, le héro subit 2 dégats",
                ],
            },
            {
                id: 2,
                name: "Nuée",
                initiative: 21,
                recycled: false,
                effects: [
                    "Déplacement +1",
                    "Attaque -1",
                    "+1 à attaque si cible adjacente à un allié de la monstruosité",
                ],
            },
            {
                id: 3,
                name: "Nuée",
                initiative: 21,
                recycled: false,
                effects: [
                    "Déplacement +1",
                    "Attaque -1",
                    "+1 à attaque si cible adjacente à un allié de la monstruosité",
                ],
            },
            {
                id: 4,
                name: "Morsure affaiblissante",
                initiative: 34,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0, confusion"],
            },
            {
                id: 5,
                name: "Rien de particulier",
                initiative: 39,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0"],
            },
            {
                id: 6,
                name: "Égratignure incertaine",
                initiative: 52,
                recycled: true,
                effects: [
                    "Déplacement +0",
                    "Attaque +1",
                    "Si l'attaque est effectuée, la monstruosité subit 1 dégat",
                ],
            },
            {
                id: 7,
                name: "Coup calculé",
                initiative: 60,
                recycled: false,
                effects: ["Déplacement -1", "Attaque +1"],
            },
            {
                id: 8,
                name: "Frénésie incertaine",
                initiative: 74,
                recycled: false,
                effects: [
                    "Déplacement +0",
                    "la monstruosité subit 1 dégat",
                    "Attaque +1, cible tous les adversaires adjacents",
                ],
            },
        ],
    },
    {
        id: "rat_monster",
        name: "Monstruosité ratine",
        normalHp: [4, 4, 5, 6, 8, 10, 12, 12],
        eliteHp: [6, 7, 8, 10, 12, 13, 14, 16],
        normalMove: [1, 1, 2, 2, 2, 3, 3, 3],
        eliteMove: [1, 1, 1, 2, 2, 2, 3, 3],
        normalAttack: [1, 2, 2, 3, 3, 3, 3, 4],
        eliteAttack: [2, 2, 3, 3, 3, 4, 4, 5],
        normalModifiers: [
            "à sa mort, tous les personnages adjacents subissent 1 dégats",
            "à sa mort, tous les personnages adjacents subissent 1 dégats",
            "à sa mort, tous les personnages adjacents subissent 1 dégats",
            "à sa mort, tous les personnages adjacents subissent 2 dégats",
            "à sa mort, tous les personnages adjacents subissent 2 dégats",
            "à sa mort, tous les personnages adjacents subissent 2 dégats",
            "à sa mort, tous les personnages adjacents subissent 3 dégats",
            "à sa mort, tous les personnages adjacents subissent 3 dégats",
        ],
        eliteModifiers: [
            "à sa mort, tous les personnages adjacents subissent 1 dégats",
            "à sa mort, tous les personnages adjacents subissent 2 dégats, avantage",
            "à sa mort, tous les personnages adjacents subissent 2 dégats, avantage",
            "à sa mort, tous les personnages adjacents subissent 2 dégats, avantage",
            "à sa mort, tous les personnages adjacents subissent 3 dégats, avantage",
            "à sa mort, tous les personnages adjacents subissent 3 dégats, avantage",
            "à sa mort, tous les personnages adjacents subissent 3 dégats, avantage",
            "à sa mort, tous les personnages adjacents subissent 4 dégats, avantage",
        ],
        actions: [
            {
                id: 1,
                name: "Bulles explosives",
                initiative: 9,
                recycled: true,
                effects: [
                    "Déplacement +1",
                    "Chaque fois qu'un héro attaque la monstruosité, le héro subit 2 dégats",
                ],
            },
            {
                id: 2,
                name: "Nuée",
                initiative: 21,
                recycled: false,
                effects: [
                    "Déplacement +1",
                    "Attaque -1",
                    "+1 à attaque si cible adjacente à un allié de la monstruosité",
                ],
            },
            {
                id: 3,
                name: "Nuée",
                initiative: 21,
                recycled: false,
                effects: [
                    "Déplacement +1",
                    "Attaque -1",
                    "+1 à attaque si cible adjacente à un allié de la monstruosité",
                ],
            },
            {
                id: 4,
                name: "Morsure affaiblissante",
                initiative: 34,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0, confusion"],
            },
            {
                id: 5,
                name: "Rien de particulier",
                initiative: 39,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0"],
            },
            {
                id: 6,
                name: "Égratignure incertaine",
                initiative: 52,
                recycled: true,
                effects: [
                    "Déplacement +0",
                    "Attaque +1",
                    "Si l'attaque est effectuée, la monstruosité subit 1 dégat",
                ],
            },
            {
                id: 7,
                name: "Coup calculé",
                initiative: 60,
                recycled: false,
                effects: ["Déplacement -1", "Attaque +1"],
            },
            {
                id: 8,
                name: "Frénésie incertaine",
                initiative: 74,
                recycled: false,
                effects: [
                    "Déplacement +0",
                    "la monstruosité subit 1 dégat",
                    "Attaque +1, cible tous les adversaires adjacents",
                ],
            },
        ],
    },
    {
        id: "vermling_bandit",
        name: "Pillard Vermling",
        normalHp: [4, 5, 9, 11, 12, 15, 17, 19],
        eliteHp: [8, 10, 14, 16, 19, 23, 27, 31],
        normalMove: [1, 1, 2, 3, 3, 3, 4, 4],
        eliteMove: [1, 1, 3, 3, 4, 4, 4, 4],
        normalAttack: [2, 2, 2, 2, 3, 3, 3, 4],
        eliteAttack: [2, 2, 3, 4, 4, 4, 5, 6],
        normalModifiers: ["", "", "", "", "", "", "", ""],
        eliteModifiers: ["", "", "", "", "", "", "", ""],
        actions: [
            {
                id: 1,
                name: "Fosse à pointes",
                initiative: 20,
                recycled: false,
                effects: [
                    "Attaque +0 (portée 4)",
                    "Créez un piège 3 dégats sur l'hexaxone vide adjacent le plus proche d'un adversaire",
                ],
            },
            {
                id: 2,
                name: "Panser les blessures",
                initiative: 30,
                recycled: true,
                effects: ["Déplacement +1", "Soin 3 sur lui-même"],
            },
            {
                id: 3,
                name: "Lancer précis",
                initiative: 36,
                recycled: false,
                effects: ["Déplacement +0", "Attaque -1, portée 4"],
            },
            {
                id: 4,
                name: "Rien de particulier",
                initiative: 50,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0"],
            },
            {
                id: 5,
                name: "Doubles dagues",
                initiative: 59,
                recycled: false,
                effects: ["Attaque +0 (portée 3, cible 2)"],
            },
            {
                id: 6,
                name: "Parade",
                initiative: 70,
                recycled: false,
                effects: ["Déplacement +0", "Attaque -1, désarmement"],
            },
            {
                id: 7,
                name: "Méchant épieu",
                initiative: 77,
                recycled: false,
                effects: ["Déplacement -1", "Attaque +0, portée 3, blessure"],
            },
            {
                id: 8,
                name: "Hurlements repoussants",
                initiative: 85,
                recycled: true,
                effects: [
                    "Poussée 1, ciblez tous les adversaires adjacents",
                    "Attaque +1, portée 2",
                ],
            },
        ],
    },
    {
        id: "black_vase",
        name: "Vase noire",
        normalHp: [4, 5, 7, 8, 9, 10, 12, 16],
        eliteHp: [8, 9, 11, 11, 13, 15, 16, 18],
        normalMove: [1, 1, 1, 1, 2, 2, 2, 2],
        eliteMove: [1, 1, 1, 2, 2, 3, 3, 3],
        normalAttack: [2, 2, 2, 3, 3, 3, 4, 4],
        eliteAttack: [2, 2, 3, 3, 4, 4, 4, 5],
        normalModifiers: [
            "",
            "Bouclier 1",
            "Bouclier 1",
            "Bouclier 1",
            "Bouclier 1",
            "Bouclier 1",
            "Bouclier 1, empoisonnement",
            "Bouclier 1, empoisonnement",
        ],
        eliteModifiers: [
            "",
            "Bouclier 1",
            "Bouclier 1",
            "Bouclier 1, empoisonnement",
            "Bouclier 1, empoisonnement",
            "Bouclier 1, empoisonnement",
            "Bouclier 2, empoisonnement",
            "Bouclier 2, empoisonnement",
        ],
        actions: [
            {
                id: 1,
                name: "Assaut précipité",
                initiative: 36,
                recycled: false,
                effects: ["Déplacement +1", "Attaque -1, portée 3"],
            },
            {
                id: 2,
                name: "Rien de particulier",
                initiative: 57,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0, portée 2"],
            },
            {
                id: 3,
                name: "Explosion toxique",
                initiative: 57,
                recycled: false,
                effects: [
                    "Attaque +0, portée 2, cible 2, empoisonnement",
                    "consume terre: +1 cible",
                ],
            },
            {
                id: 4,
                name: "Coup calculé",
                initiative: 66,
                recycled: false,
                effects: ["Déplacement -1", "Attaque +1, portée 3"],
            },
            {
                id: 5,
                name: "Repas",
                initiative: 66,
                recycled: false,
                effects: [
                    "Déplacement +0",
                    "Pillage 1",
                    "Soin 2 sur elle-même",
                    "consume obscurité: +1 soin",
                ],
            },
            {
                id: 6,
                name: "Sceau Plasmique",
                initiative: 85,
                recycled: false,
                effects: [
                    "Poussée 1, empoisonnement, cible tous adversaires adjacents",
                    "Attaque +1, portée 2",
                ],
            },
            {
                id: 7,
                name: "Noire damnation",
                initiative: 85,
                recycled: true,
                effects: [
                    "L'adversaire en ligne de vue le plus proche, sans considération de portée, subit 1+NS/2 dégats (arrondis au supérieur)",
                    "Soin 1 sur elle-même",
                    "Infuse obscurité",
                ],
            },
            {
                id: 8,
                name: "Damnation infectieuse",
                initiative: 85,
                recycled: true,
                effects: [
                    "L'adversaire en ligne de vue le plus proche, sans considération de portée, subit 1+NS/2 dégats (arrondis au supérieur)",
                    "Soin 1 sur elle-même",
                    "Infuse terre",
                ],
            },
        ],
    },
    {
        id: "giant_viper",
        name: "Vipère géante",
        normalHp: [2, 3, 4, 4, 6, 7, 8, 10],
        eliteHp: [3, 5, 7, 8, 11, 13, 14, 18],
        normalMove: [2, 2, 3, 3, 3, 3, 4, 4],
        eliteMove: [2, 2, 3, 3, 3, 4, 4, 4],
        normalAttack: [1, 1, 1, 2, 2, 3, 3, 3],
        eliteAttack: [2, 2, 2, 3, 3, 3, 4, 4],
        normalModifiers: [
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
        ],
        eliteModifiers: [
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
            "empoisonnement",
        ],
        actions: [
            {
                id: 1,
                name: "Crocs rapides",
                initiative: 33,
                recycled: false,
                effects: ["Déplacement +1, saut", "Attaque +0, cible 2"],
            },
            {
                id: 2,
                name: "À couvert",
                initiative: 18,
                recycled: false,
                effects: [
                    "Déplacement +1, saut",
                    "Attaque -1",
                    "Toutes les attaques ciblant la vipère gagnent désavantage ce round",
                ],
            },
            {
                id: 3,
                name: "Coup calculé",
                initiative: 58,
                recycled: false,
                effects: ["Déplacement -1", "Attaque +1"],
            },
            {
                id: 4,
                name: "Frénésie toxique",
                initiative: 43,
                recycled: false,
                effects: [
                    "Déplacement +1, saut",
                    "Attaque -1, cible tous adversaires adjacents",
                ],
            },
            {
                id: 5,
                name: "Cerner",
                initiative: 32,
                recycled: true,
                effects: [
                    "Déplacement +0",
                    "Attaque +0",
                    "Ajoute +2 attaque si la cible est adjacente à un allié de la vipère",
                ],
            },
            {
                id: 6,
                name: "Cerner",
                initiative: 32,
                recycled: true,
                effects: [
                    "Déplacement +0",
                    "Attaque +0",
                    "Ajoute +2 attaque si la cible est adjacente à un allié de la vipère",
                ],
            },
            {
                id: 7,
                name: "Coup Défensif",
                initiative: 11,
                recycled: false,
                effects: ["Bouclier 1", "Attaque +0"],
            },
            {
                id: 8,
                name: "Constriction",
                initiative: 23,
                recycled: false,
                effects: [
                    "Déplacement -1",
                    "Attaque -1, immobilisation",
                    "Attaque -1",
                ],
            },
        ],
    },
    {
        id: "zealot",
        name: "Zélote",
        normalHp: [4, 6, 7, 8, 10, 12, 14, 16],
        eliteHp: [7, 8, 11, 13, 17, 18, 22, 26],
        normalMove: [2, 2, 3, 3, 3, 4, 4, 4],
        eliteMove: [2, 2, 3, 3, 3, 4, 4, 4],
        normalAttack: [2, 2, 3, 3, 3, 3, 4, 5],
        eliteAttack: [3, 3, 3, 4, 4, 5, 6, 7],
        normalModifiers: [
            "",
            "",
            "",
            "blessure",
            "blessure",
            "blessure",
            "blessure",
            "blessure",
        ],
        eliteModifiers: [
            "",
            "blessure",
            "blessure",
            "blessure",
            "blessure",
            "blessure",
            "blessure",
            "blessure",
        ],
        actions: [
            {
                id: 1,
                name: "Fouet de damnation",
                initiative: 19,
                recycled: false,
                effects: [
                    "Déplacement +1, saut",
                    "Attaque -1, malédiction",
                    "infuse air",
                ],
            },
            {
                id: 2,
                name: "Drain de vie",
                initiative: 27,
                recycled: true,
                effects: [
                    "Déplacement +0",
                    "Attaque -1 (portée 2)",
                    "Soin X sur lui-même (X=montant dégat attaque)",
                    "infuse Obscurité",
                ],
            },
            {
                id: 3,
                name: "Assaut précipité",
                initiative: 35,
                recycled: false,
                effects: ["Déplacement +1", "Attaque -1"],
            },
            {
                id: 4,
                name: "Sang bouillant",
                initiative: 46,
                recycled: false,
                effects: [
                    "Attaque -1, portée 2, cible 2, confusion",
                    "Consume feu: +2 portée",
                ],
            },
            {
                id: 5,
                name: "Rien de particulier",
                initiative: 50,
                recycled: false,
                effects: ["Déplacement +0", "Attaque +0"],
            },
            {
                id: 6,
                name: "Coup calculé",
                initiative: 0,
                recycled: false,
                effects: ["Déplacement -1", "Attaque +1"],
            },
            {
                id: 7,
                name: "Fléau infame",
                initiative: 77,
                recycled: false,
                effects: [
                    "Déplacement -1",
                    "Attaque -1, empoisonnement (cible 2 hexes adjacents voisins",
                    "Consume air: +1 attaque",
                ],
            },
            {
                id: 8,
                name: "Flamme impie",
                initiative: 0,
                recycled: true,
                effects: ["Attaque +1, portée 3", "Infuse feu"],
            },
        ],
    },
    {
        id: "blood_horror",
        name: "Horreur de sang",
        boss: true,
        hp: [
            (a) => 7 * a,
            (a) => 10 * a,
            (a) => 12 * a,
            (a) => 15 * a,
            (a) => 17 * a,
            (a) => 20 * a,
            (a) => 23 * a,
            (a) => 28 * a,
        ],
        move: [3, 3, 4, 4, 5, 5, 5, 5],
        attack: [
            (a) => a - 1,
            (a) => a,
            (a) => a,
            (a) => a + 1,
            (a) => a + 1,
            (a) => a + 2,
            (a) => a + 3,
            (a) => a + 4,
        ],
        immunities: [
            "immobilisation",
            "désarmement",
            "confusion",
            "étourdissement",
        ],
        special1: [
            () =>
                `saute jusqu'au zélote mort le plus éloigné et le ressuscite, ou saute jusqu'a l'aventurier le plus éloigné et Attaque +0`,
            () =>
                `saute jusqu'au zélote mort le plus éloigné et le ressuscite, ou saute jusqu'a l'aventurier le plus éloigné et Attaque +0`,
            () =>
                `saute jusqu'au zélote mort le plus éloigné et le ressuscite, ou saute jusqu'a l'aventurier le plus éloigné et Attaque +0`,
            () =>
                `saute jusqu'au zélote mort le plus éloigné et le ressuscite, ou saute jusqu'a l'aventurier le plus éloigné et Attaque +0`,
            () =>
                `saute jusqu'au zélote mort le plus éloigné et le ressuscite, ou saute jusqu'a l'aventurier le plus éloigné et Attaque +0`,
            () =>
                `saute jusqu'au zélote mort le plus éloigné et le ressuscite, ou saute jusqu'a l'aventurier le plus éloigné et Attaque +0`,
            () =>
                `saute jusqu'au zélote mort le plus éloigné et le ressuscite, ou saute jusqu'a l'aventurier le plus éloigné et Attaque +0`,
            () =>
                `saute jusqu'au zélote mort le plus éloigné et le ressuscite, ou saute jusqu'a l'aventurier le plus éloigné et Attaque +0`,
        ],
        special2: [
            () =>
                `déplacement +0, attaque +0. ressuscite tous les zélotes morts dans la salle`,
            () =>
                `déplacement +0, attaque +0. ressuscite tous les zélotes morts dans la salle`,
            () =>
                `déplacement +0, attaque +0. ressuscite tous les zélotes morts dans la salle`,
            () =>
                `déplacement +0, attaque +0. ressuscite tous les zélotes morts dans la salle`,
            () =>
                `déplacement +0, attaque +0. ressuscite tous les zélotes morts dans la salle`,
            () =>
                `déplacement +0, attaque +0. ressuscite tous les zélotes morts dans la salle`,
            () =>
                `déplacement +0, attaque +0. ressuscite tous les zélotes morts dans la salle`,
            () =>
                `déplacement +0, attaque +0. ressuscite tous les zélotes morts dans la salle`,
        ],
        actions: BOSS_ACTIONS,
    },
    {
        id: "primat_de_ordre",
        name: "Primat de l'Ordre",
        boss: true,
        hp: [
            (a) => 10 * a,
            (a) => 14 * a,
            (a) => 17 * a,
            (a) => 20 * a,
            (a) => 24 * a,
            (a) => 28 * a,
            (a) => 32 * a,
            (a) => 36 * a,
        ],
        move: [2, 2, 2, 2, 3, 3, 3, 3],
        attack: [
            () => 3,
            () => 4,
            () => 4,
            () => 5,
            () => 5,
            () => 6,
            () => 7,
            () => 8,
        ],
        immunities: [
            "immobilisation",
            "désarmement",
            "confusion",
            "étourdissement",
            "malédiction",
        ],
        special1: [
            (a) =>
                `tous les adversaires à portée 2 subissent 2 dégats, générez ${a / 2} diablotins de sang`,
            (a) =>
                `tous les adversaires à portée 2 subissent 2 dégats, générez ${a / 2} diablotins de sang`,
            (a) =>
                `tous les adversaires à portée 2 subissent 2 dégats, générez ${a / 2} diablotins de sang`,
            (a) =>
                `tous les adversaires à portée 2 subissent 2 dégats, générez ${a / 2} diablotins de sang`,
            (a) =>
                `tous les adversaires à portée 2 subissent 2 dégats, générez ${a / 2} diablotins de sang`,
            (a) =>
                `tous les adversaires à portée 2 subissent 2 dégats, générez ${a / 2} diablotins de sang`,
            (a) =>
                `tous les adversaires à portée 2 subissent 2 dégats, générez ${a / 2} diablotins de sang`,
            (a) =>
                `tous les adversaires à portée 2 subissent 2 dégats, générez ${a / 2} diablotins de sang`,
        ],
        special2: [
            () =>
                `attaque +0, attaque -1 à portée 2 de la cible, attaque -2 à portée 2 de la cible`,
            () =>
                `attaque +0, attaque -1 à portée 2 de la cible, attaque -2 à portée 2 de la cible`,
            () =>
                `attaque +0, attaque -1 à portée 2 de la cible, attaque -2 à portée 2 de la cible`,
            () =>
                `attaque +0, attaque -1 à portée 2 de la cible, attaque -2 à portée 2 de la cible`,
            () =>
                `attaque +0, attaque -1 à portée 2 de la cible, attaque -2 à portée 2 de la cible`,
            () =>
                `attaque +0, attaque -1 à portée 2 de la cible, attaque -2 à portée 2 de la cible`,
            () =>
                `attaque +0, attaque -1 à portée 2 de la cible, attaque -2 à portée 2 de la cible`,
            () =>
                `attaque +0, attaque -1 à portée 2 de la cible, attaque -2 à portée 2 de la cible`,
        ],
        actions: BOSS_ACTIONS,
    },
    {
        id: "tumeur_de_sang",
        name: "Tumeur de Sang",
        boss: true,
        hp: [
            (a) => 7 * a,
            (a) => 10 * a,
            (a) => 12 * a,
            (a) => 15 * a,
            (a) => 17 * a,
            (a) => 20 * a,
            (a) => 23 * a,
            (a) => 28 * a,
        ],
        move: [0, 0, 0, 0, 0, 0, 0, 0],
        attack: [
            (a) => a - 1,
            (a) => a,
            (a) => a,
            (a) => a + 1,
            (a) => a + 1,
            (a) => a + 2,
            (a) => a + 2,
            (a) => a + 3,
        ],
        immunities: ["désarmement", "confusion", "étourdissement"],
        special1: [
            (a) => `Soin ${a} sur elle-même`,
            (a) => `Soin ${a} sur elle-même`,
            (a) => `Soin ${a + 1} sur elle-même`,
            (a) => `Soin ${a + 1} sur elle-même`,
            (a) => `Soin ${a + 2} sur elle-même`,
            (a) => `Soin ${a + 2} sur elle-même`,
            (a) => `Soin ${a + 3} sur elle-même`,
            (a) => `Soin ${a + 3} sur elle-même`,
        ],
        special2: [
            () => `Soin 2 sur tous les alliés`,
            () => `Soin 2 sur tous les alliés`,
            () => `Soin 3 sur tous les alliés`,
            () => `Soin 3 sur tous les alliés`,
            () => `Soin 4 sur tous les alliés`,
            () => `Soin 4 sur tous les alliés`,
            () => `Soin 5 sur tous les alliés`,
            () => `Soin 5 sur tous les alliés`,
        ],
        actions: BOSS_ACTIONS,
    },
];

const ENEMIES_MAP = {};
for (let enemies of ENEMIES) {
    ENEMIES_MAP[enemies.id] = enemies;
}
